import pyautogui as pg
import time

N = int(input(">> "))
#pg.click(518, 743, clicks=1, interval=0.5)
#pg.press('F11', presses=1)
pg.click(848, 760, clicks=1, interval=0.5)
#pg.moveTo(1200,770)
#pg.hotkey('winleft','printscreen')
time.sleep(1)
for i in range(N):
    pg.press('right', presses=1)
    time.sleep(0.5)
    pg.press('enter', presses=1)
    time.sleep(0.5)
    pg.hotkey('ctrl', 'a')
    time.sleep(0.5)
    pg.rightClick(231, 245)
    time.sleep(0.6)
    #pg.hotkey('shift', 'm')
    pg.hotkey('shift', 'm')
    time.sleep(0.3)
    #pg.press('enter', presses=1)
    time.sleep(0.3)
    pg.hotkey('shift', 'b')
    time.sleep(0.3)
    pg.press('enter', presses=1)
    time.sleep(4)
    pg.hotkey('alt', 'left')
    time.sleep(0.6)
